---
####### Set AWS GovCloud Credentials
- name: '{{ ansible_name_module}} | template | Place AWS Credentials'
  template:
    src: "aws-credentials.yaml.j2"
    dest: "{{ dir_secrets }}/aws/credentials"

- name: '{{ ansible_name_module }} | copy | Place AWS Credentials'
  copy:
    src: "{{ dir_secrets }}/aws/credentials"
    dest: "{{ local_home }}/.aws/credentials"


