---
- name: '{{ ansible_name_module }} | include_tasks | aws.yml' 
  include_tasks: aws.yml

- name: '{{ ansible_name_module }} | include_tasks | ssh.yml' 
  include_tasks: ssh.yml

- name: '{{ ansible_name_module }} | include_tasks | registry.yml' 
  include_tasks: registry.yml

- name: '{{ ansible_name_module }} | include_tasks | htpasswd.yml' 
  include_tasks: htpasswd.yml

# name: '{{ ansible_name_module }} | include_tasks | ssl.yml' 
# include_tasks: ssl.yml
