---
####### Self Signed Certs for registry
- name: '{{ ansible_name_module }} | ssl | openssl_privatekey | Registry FQDN Private Key'
  openssl_privatekey:
    path: "{{ dir_secrets }}/registry/ssl/registry.{{ cluster_domain }}.key"
    size: 4096

- name: '{{ ansible_name_module }} | ssl | openssl_csr | Registry FQDN Certificate Signing Request'
  openssl_csr:
    path: "{{ dir_secrets }}/registry/ssl/registry.{{ cluster_domain }}.csr"
    privatekey_path: "{{ dir_secrets }}/registry/ssl/registry.{{ cluster_domain }}.key"
    common_name: "registry"
    subject_alt_name:
      - "DNS:registry.{{ cluster_domain }}"
      - "DNS:{{ name_dns_cloudctl }}"
      - "DNS:{{ name_dns_registry }}"
      - "DNS:{{ name_dns_localhost }}"
      - "DNS:{{ name_dns_addr_cni }}"
      - "DNS:{{ name_dns_addr_host }}"
#     - "DNS:{{ name_ip_cloudctl }}"

- name: '{{ ansible_name_module }} | ssl | openssl_certificate | Generate FQDN Registry Certificates | Self Signed + 365 Day TTL'
  openssl_certificate:
    path: "{{ dir_secrets }}/registry/ssl/registry.{{ cluster_domain }}.crt"
    privatekey_path: "{{ dir_secrets }}/registry/ssl/registry.{{ cluster_domain }}.key"
    csr_path: "{{ dir_secrets }}/registry/ssl/registry.{{ cluster_domain }}.csr"
    selfsigned_not_after: "+365d"
    selfsigned_digest: "sha256"
    provider: selfsigned
