---
- name: ocp4-deploy | task01-init | Clone Git repositories
  git:
    clone: yes
    dest: "{{ item.dest }}"
    repo: "{{ item.repo }}"
  with_items:
    - "{{ gitrepos }}"

- name: ocp4-deploy | task01-init | Create manifest
  shell: "openshift-install create manifests --dir={{ lookup('env','dirArtifacts') }}/data"

