---
- name: '{{ ansible_name_module }} | file | Create Directory Structure' 
  file:
    path: '{{ item }}'
    state: directory
    mode: '0777'
  with_items:
    - '{{ dir_platform }}/nginx'
- name: '{{ ansible_name_module }} | copy | Load Ignition Files into Nginx Service'
  copy:
    src: "{{ dir_platform }}/cluster/ignition/"
    dest: "{{ dir_platform }}/nginx/"
    mode: 0777
