---
# defaults file for task03-deploy
artifact_directory: "{{ lookup('env','dirArtifacts') }}"
base_directory: "{{ lookup('env','dirBase') }}"
cluster_name: "{{ lookup('env','nameCluster') }}"
cluster_domain: "{{ lookup('env','clusterDomain') }}"
ec2_region: "{{ lookup('env', 'awsRegion1') }}"
home_directory: "{{ lookup('env','HOME') }}"
ocp_version: "{{ lookup('env','versOCP') }}"
remote_home: "{{ ansible_env.HOME }}"
vpc_name: "{{ lookup('env','nameVpc') }}"
domain_name: "{{ lookup('env','nameDomain') }}"
ocp_tag: 


#Terraform spin-up
TF_VAR_infrastructure_id: "{{ vpc_name }}"
TF_VAR_aws_region: "{{ ec2_region }}"
TF_VAR_clustername: "{{ cluster_name }}"
TF_VAR_domain: "{{ domain_name }}"
AWS_DEFAULT_REGION: "{{ ec2_region }}"

# point the ignition files to the proper location
TF_VAR_registry_ssh_public_key_file_path: "{{ artifact_directory }}/.ssh/id_rsa_{{ cluster_domain }}.pub"
TF_VAR_bastion_ssh_public_key_file_path: "{{ artifact_directory }}/.ssh/id_rsa_{{ cluster_domain }}.pub"
TF_VAR_master_ign_path: "{{ artifact_directory }}/data/master.ign"
TF_VAR_bootstrap_ign_path: "{{ artifact_directory }}/data/bootstrap.ign"


#Terraform variable to deploy 
tf_base_dir: "{{ lookup('env', 'dirBase') }}/terraform/aws-platform-base"

# Setting vars for future region support
#ec2_region1: "{{ lookup('env', 'awsRegion1') }}"
#ec2_region2: "{{ lookup('env', 'awsRegion2') }}"
#ec2_region3: "{{ lookup('env', 'awsRegion3') }}"
