---
- name: '{{ ansible_name_module }} | command:skopeo.copy | Pull CloudCTL Pod Images' 
  command:
    argv:
      - skopeo
      - copy
      - 'docker://{{ item.uri }}/{{ item.name }}:{{ item.tag }}'
      - 'docker-archive://{{ item.path }}/image-{{ item.name }}-{{ item.tag }}.tar'
      - --additional-tag
      - '{{ item.uri }}/{{ item.name }}:cloudctl'
    creates: "{{ dir_platform }}/images/image-{{ item.name }}-{{ item.tag }}.tar"
  with_items:
    - "{{ images_cloudctl }}"

- name: '{{ ansible_name_module }} | command:skopeo.copy | Pull Pause Images' 
  command:
    argv:
      - skopeo
      - copy
      - 'docker://{{ item.uri }}/{{ item.name }}:{{ item.tag }}'
      - 'docker-archive://{{ item.path }}/image-{{ item.name }}-{{ item.tag }}.tar'
      - --additional-tag
      - '{{ item.uri }}/{{ item.name }}:{{ item.tag }}'
    creates: "{{ dir_platform }}/images/image-{{ item.name }}-{{ item.tag }}.tar"
  with_items:
    - "{{ images_pause }}"
