---
- name: '{{ ansible_name_module }} | stat | check for mirror v2.sha256'
  stat:
    path: '{{ dir_deploy }}/mirror/ocp-release.{{ version_openshift }}.lock'
  register: mirror_lock_check

###### Download OpenShift Docker Images from Quay.io to File: /root/deploy/mirror/v2
- name: '{{ ansible_name_module }} | block | Download OpenShift images'
  block:

  ######### Purge & Prepare
    - name: '{{ ansible_name_module }} | file:directory | Create mirror artifact directories'
      file:
        path: "{{ dir_deploy }}/mirror"
        state: directory

  ######### Mirror Images to directory
    - name: '{{ ansible_name_module }} | shell:oc.adm.release.mirror | Sync content from quay.io'
      shell: |
        oc adm release mirror --insecure=true \
          --to=localhost:5000/openshift-release-dev \
          --registry-config=/root/.docker/config.json \
          --from=quay.io/openshift-release-dev/ocp-release:{{ version_openshift }}-x86_64 \
          --to-release-image=localhost:5000/openshift-release-dev:{{ version_openshift }}-x86_64
#     when: image_mirror_utility == "oc"
 
# ######### Skopeo Copy Images to Registry
#   - name: '{{ ansible_name_module }} | shell:skopeo.copy | Sync content from quay.io'
#     shell: |
#         for i in $(cat /var/lib/koffer/release.list); do \
#           skopeo copy docker://quay.io/$i \
#           docker://localhost:5000/$i ; \
#         done
#     when: image_mirror_utility == "skopeo"

  ####### Block Conditionals
  when: not mirror_lock_check.stat.exists

- name: '{{ ansible_name_module }} | command:touch | Place mirror lock file'
  command:
    cmd: 'touch {{ dir_deploy }}/mirror/ocp-release.{{ version_openshift }}.lock'
  args:
    warn: false
